package utils;

public enum WordTypes {
	ADJECTIVE, ADVERB, DETERMINER, PREDETERMINER, NUMERALS, CONJUNCTION, NOUN, OTHER, PREPOSITION, PRONOUN, PARTICLES, PUNCTUATION, VERB, NAMED_ENTITY, NOT_DETECTED

}